---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: List bucket facts
      oci_object_storage_bucket_facts:
         namespace_name: 'levy2018'
         compartment_id: 'ocid1.tenancy.oc1..aaaaaaaakxddfwoe2okuqh2kr4fgc7ogwh36sl6yfs37dlcczsafsft5ti2q'
      register: result
    - name: Dump result
      debug: 
        msg: '{{result}}'
